define [], () ->
  class svgDefs

    addDefs: (def) ->
      def
        .append('svg:marker')
          .attr('id', 'draghead')
          .attr('viewBox', '0 -5 10 10')
          .attr('refX', '5')
          .attr('refY', '0')
          .attr('markerWidth', '3')
          .attr('markerHeight', '3')
          .attr('orient', 'auto')
          .attr('fill', 'black')
          .append('svg:path')
            .attr('d',"M0,-5L10,0L0,5")
      def
        .append('svg:marker')
          .attr('id', 'arrowhead')
          .attr('viewBox', '0 -5 10 10')
          .attr('refX', '40')
          .attr('refY', '0')
          .attr('markerWidth', '4')
          .attr('markerHeight', '4')
          .attr('orient', 'auto')
          .attr('fill', '#ccc')
          .append('svg:path')
            .attr('d',"M0,-5L10,0L0,5")
      def
        .append('svg:marker')
          .attr('id', 'arrowhead-selected')
          .attr('viewBox', '0 -5 10 10')
          .attr('refX', '40')
          .attr('refY', '0')
          .attr('markerWidth', '4')
          .attr('markerHeight', '4')
          .attr('orient', 'auto')
          .attr('fill', '#3498db')
          .append('svg:path')
            .attr('d',"M0,-5L10,0L0,5")